# Generated by Django 3.2.5 on 2022-02-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='books',
            name='category',
            field=models.CharField(max_length=30),
        ),
    ]
